### ISSUE TITLE
Timeout exceeded for all JS labs

### ISSUE THREAD

**Issue by Rollo510** [learn-co-curriculum/fewpjs-removing-altering-and-inserting-html-lab#9]
There's a recurring issue where all of the labs that use Mocha are running into a Timeout exception error.  I've spoken to another student and he's running into the same issue.  

```
1) "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:312:18)
      at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
